<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'controller_resolver' shared service.

return $this->services['controller_resolver'] = new \Bundles\FrameworkBundle\Controller\ContainerAwareControllerResolver(${($_ = isset($this->services['log']) ? $this->services['log'] : $this->services['log'] = new \Bundles\FrameworkBundle\Log\Log(($this->targetDirs[1].'/logs/log_project_127.0.0.1:8080.log'))) && false ?: '_'}, $this);
