<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'routing.matcher_factory' shared service.

return $this->services['routing.matcher_factory'] = new \Bundles\FrameworkBundle\Routing\URLMatcherFactory(${($_ = isset($this->services['router']) ? $this->services['router'] : $this->load('getRouterService.php')) && false ?: '_'}, ${($_ = isset($this->services['context']) ? $this->services['context'] : $this->services['context'] = new \Symfony\Component\Routing\RequestContext()) && false ?: '_'});
