<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'routing.route_collection' shared service.

return $this->services['routing.route_collection'] = new \Symfony\Component\Routing\RouteCollection();
