<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'session.session_listener' shared service.

return $this->services['session.session_listener'] = new \Bundles\FrameworkBundle\Session\SessionListener($this);
