<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'config' shared service.

return $this->services['config'] = new \Bundles\FrameworkBundle\Config\Config($this);
