<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'listener.view_response' shared service.

return $this->services['listener.view_response'] = new \Bundles\FrameworkBundle\Response\Listeners\ViewResponseListener();
