<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'locale.local_listener' shared service.

return $this->services['locale.local_listener'] = new \Bundles\FrameworkBundle\Locale\LocaleListener();
