<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'request_stack' shared service.

return $this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack();
