<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'request' shared service.

return $this->services['request'] = ${($_ = isset($this->services['request.factory']) ? $this->services['request.factory'] : $this->services['request.factory'] = new \Bundles\FrameworkBundle\Request\RequestFactory()) && false ?: '_'}->create();
