<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'session.pdo_session_handler' shared service.

return $this->services['session.pdo_session_handler'] = new \Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler(${($_ = isset($this->services['db']) ? $this->services['db'] : $this->load('getDbService.php')) && false ?: '_'});
