<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'session.save_session_listener' shared service.

return $this->services['session.save_session_listener'] = new \Symfony\Component\HttpKernel\EventListener\SaveSessionListener();
