<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'template' shared service.

$this->services['template'] = $instance = new \Bundles\FrameworkBundle\Template\Template(${($_ = isset($this->services['twig.environment']) ? $this->services['twig.environment'] : $this->load('getTwig_EnvironmentService.php')) && false ?: '_'});

$instance->addTemplateDir('resources/views');

return $instance;
