<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.loader' shared service.

return $this->services['twig.loader'] = new \Twig_Loader_Filesystem('app', $this->targetDirs[2]);
