#!/usr/bin/env php
<?php
/**
 * The Hero Framework.
 *
 * (c) Celso Luiz de F. Fernandes  <celso@thephphero.com>
 * Date: 18/08/17
 * Time: 20:43
 * Created by thePHPHero
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */



require __DIR__ . '/bootstrap/autoload.php';

use Bundles\FrameworkBundle\Console\Application;

$app = new \Core\Application(__DIR__,getenv('ENVIRONMENT'),getenv('DEBUG'));

$application = new Application($app,'HeroFramework','1.0');

$output = new \Symfony\Component\Console\Output\ConsoleOutput();

$output->writeln(' Welcome to HERO');

$application->run();