framework:

  # Error Display
  # During the development, it is useful to show warnings and errors on the screen. If
  # error_display is set to true, all warning, notices and errors will be displayed to
  # the user. In a production environment it is common to set this to false
  #
  error_controller: 'App\\common\\ErrorController::exception'
  #SSL
  # If the config_ssl variable is set to true, the router will always place a https schema
  # when building urls.
  #
  config_ssl: false


  # Session Driver
  # Currently, sessions may be saved in the database or as a file on the server. By changing the
  # values below it is possible to select the preferred method (database or file)
  #
  session_driver: 'database'
  session_dir: 'storage/sessions'

  # Log Directories
  # This defines where logs generated during runtime should be stored. Webserver user must have write
  # acess to this directory
  # If you are not sure, leave as is is
  log_dir: 'storage/logs'

  # Uploads Directories
  # This is where the files uploaded by users should be stored. A sub-folder will be created automatically
  # for each project. Webserver user must have write acess to this directory
  # If you are not sure, leave as is is
  upload_dir: 'public/uploads'

  # Http Cache Directory
  # Directory where http cache files will be stored
  # Webserver user must have write acess to this directory
  # If you are not sure, leave as is is
  http_cache_dir: 'uploads/cache'

  # Default Mandrill Key
  # This is the default mandrill key to be used when clients have not entered their own key
  mandrill_default_key: ''


  # Timezone for the software
  # This sets the timezone used to determine the current time and date during runtime.
  # Default: Asia/Shanghai
  kernel.timezone: 'Europe/Berlin'

  # Exception Handler Controller
  # Register the controller and method used to display the default error page when an exceptio is
  # thrown. Example: \\App\\common\\ErrorController::exception
  exception_controller: '\\App\\common\\ErrorController::exception'
