<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'context' shared service.

return $this->services['context'] = new \Symfony\Component\Routing\RequestContext();
