<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'listener.middleware' shared service.

return $this->services['listener.middleware'] = new \Bundles\FrameworkBundle\Routing\Listeners\MiddlewareListener($this);
