<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'matcher' shared service.

return $this->services['matcher'] = ${($_ = isset($this->services['routing.matcher_factory']) ? $this->services['routing.matcher_factory'] : $this->load('getRouting_MatcherFactoryService.php')) && false ?: '_'}->create(${($_ = isset($this->services['routing.route_collection']) ? $this->services['routing.route_collection'] : $this->services['routing.route_collection'] = new \Symfony\Component\Routing\RouteCollection()) && false ?: '_'}, ${($_ = isset($this->services['context']) ? $this->services['context'] : $this->services['context'] = new \Symfony\Component\Routing\RequestContext()) && false ?: '_'});
