<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'response.listener' shared service.

return $this->services['response.listener'] = new \Symfony\Component\HttpKernel\EventListener\ResponseListener('UTF-8');
