<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'session.session_storage' shared service.

return $this->services['session.session_storage'] = new \Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage(array(), ${($_ = isset($this->services['session.pdo_session_handler']) ? $this->services['session.pdo_session_handler'] : $this->load('getSession_PdoSessionHandlerService.php')) && false ?: '_'});
