<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'session' shared service.

return $this->services['session'] = new \Symfony\Component\HttpFoundation\Session\Session(${($_ = isset($this->services['session.session_storage']) ? $this->services['session.session_storage'] : $this->load('getSession_SessionStorageService.php')) && false ?: '_'});
