<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'url_generator' shared service.

return $this->services['url_generator'] = new \Symfony\Component\Routing\Generator\UrlGenerator(${($_ = isset($this->services['routing.route_collection']) ? $this->services['routing.route_collection'] : $this->services['routing.route_collection'] = new \Symfony\Component\Routing\RouteCollection()) && false ?: '_'}, ${($_ = isset($this->services['context']) ? $this->services['context'] : $this->services['context'] = new \Symfony\Component\Routing\RequestContext()) && false ?: '_'}, ${($_ = isset($this->services['log']) ? $this->services['log'] : $this->services['log'] = new \Bundles\FrameworkBundle\Log\Log(($this->targetDirs[1].'/logs/log_project_127.0.0.1:8082.log'))) && false ?: '_'});
