<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDrfwidf\HeroFrameworkDevelopmentDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDrfwidf/HeroFrameworkDevelopmentDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDrfwidf.legacy');

    return;
}

if (!\class_exists(HeroFrameworkDevelopmentDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDrfwidf\HeroFrameworkDevelopmentDebugProjectContainer::class, HeroFrameworkDevelopmentDebugProjectContainer::class, false);
}

return new \ContainerDrfwidf\HeroFrameworkDevelopmentDebugProjectContainer(array(
    'container.build_hash' => 'Drfwidf',
    'container.build_id' => 'c68c7530',
    'container.build_time' => 1544799823,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDrfwidf');
