<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAxjzbag\HeroFrameworkDevelopmentDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAxjzbag/HeroFrameworkDevelopmentDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAxjzbag.legacy');

    return;
}

if (!\class_exists(HeroFrameworkDevelopmentDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAxjzbag\HeroFrameworkDevelopmentDebugProjectContainer::class, HeroFrameworkDevelopmentDebugProjectContainer::class, false);
}

return new \ContainerAxjzbag\HeroFrameworkDevelopmentDebugProjectContainer([
    'container.build_hash' => 'Axjzbag',
    'container.build_id' => '6904f4cb',
    'container.build_time' => 1550959310,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAxjzbag');
