<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8mkx0vo\HeroFrameworkDevelopmentDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8mkx0vo/HeroFrameworkDevelopmentDebugProjectContainer.php') {
    touch(__DIR__.'/Container8mkx0vo.legacy');

    return;
}

if (!\class_exists(HeroFrameworkDevelopmentDebugProjectContainer::class, false)) {
    \class_alias(\Container8mkx0vo\HeroFrameworkDevelopmentDebugProjectContainer::class, HeroFrameworkDevelopmentDebugProjectContainer::class, false);
}

return new \Container8mkx0vo\HeroFrameworkDevelopmentDebugProjectContainer(array(
    'container.build_hash' => '8mkx0vo',
    'container.build_id' => '472f144b',
    'container.build_time' => 1548260928,
), __DIR__.\DIRECTORY_SEPARATOR.'Container8mkx0vo');
