# app/config/security.yml
security:
  #Access denied route
  access_denied_url:    ~ # Example: /foo/error403
  # strategy can be: none, migrate, invalidate
  session_fixation_strategy:  migrate
  hide_user_not_found:  true
  always_authenticate_before_granting:  false
  erase_credentials:    true
  access_decision_manager:
    strategy:             affirmative # One of affirmative, consensus, unanimous
    allow_if_all_abstain:  false
    allow_if_equal_granted_denied:  true
  #Password enconders
  encoders:
    Library\Security\Users\User:
      algorithm:            bcrypt
      cost:                 15
    Library\Security\Users\Customer:
      algorithm:            sha256
  #User providers
  providers:
    chain_provider:
      chain:
        providers: [ default , token ]
    default:
      id: security.provider.user
    token:
      id: security.provider.token

  #Software firewall definitions
  firewalls:
    api:
      pattern: ^/api
      stateless: true
      anonymous: true
      #guard:
      #  authenticators: [security.token.authenticator]
      #  provider: token
    main:
      security:     true
      anonymous:    true
      switch_user:  true
      pattern:      ./*
      access_denied_handler: security.access_denied_handler
      entry_point: security.guard.form.authenticator
      guard:
        authenticators: [security.guard.form.authenticator]
      logout:
        path:           /logout
        target:         /
        csrf_parameter: _csrf_token
        csrf_token_id:  logout
        csrf_token_generator: csrf.token_manager
      remember_me:
        secret:   noshpos.cn
        lifetime: 15780000 #6 months
        path:     /
        name:     REMEMBERME
        always_remember_me: true
    #Access Control
  access_control:
    - { path: ^/admin, roles: [ROLE_ADMIN,ROLE_SUPERVISOR,ROLE_MANAGER] }
    - { path: ^/api, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
    #User role hierarchy
  role_hierarchy:
    ROLE_ADMIN:      [ROLE_USER]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]


